// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef valuators_h
#define valuators_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <stdio.h>
#include <FL/Fl_Box.H>
#include "grs-window.cxx"

#include <config.h>
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/math.h>
#endif
